name: Build Docker Image

on:
  push
  # branches:
  #   - main

jobs:
  run_example_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: print out example job
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: |
            echo "Nice Job!!!"
            whoami
            neofetch
  # publish:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Build and publish
  #       uses: pennsignals/publish_docker-compose@v0.1.0
  #       with:
  #         version: "latest"
  #         docker_compose: "docker-compose.yml"
  #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
